### ISSUE TITLE
Rarefaction?

### ISSUE THREAD

**Issue by DaniGargya** [DaniGargya/dissertation#4]
Hey @gndaskalova  and @IslaMS ,

I have calculated how many studies and time-series fall into specific area extents (bigger/smaller than 96km²) and have fixed plots (using HAS_PLOT, but I also saw NUMBER_LAT_LONG, which confused me a bit?). 

There are 19 studies with 1357 time-series which have areas > 96km² and 120 studies with 7016 time-series <= 96km².

There are 94 studies with 8373 time-series with fixed plots, 14 studies/ 816 time-series some fixed and 31 studies/165 time series not fixed.

**Does this mean I can exclude the studies which areas > 96km² and not do a rarefaction?**

@gndaskalova do you have some spare time towards the end of the week, to quickly meet up and discuss some things related to the data? or would you prefer me sending you a list of questions for now and meet up next week?

**Comment by gndaskalova** [comment]
Hi @DaniGargya @IslaMS 

Can I just check that you are referring to terrestrial studies Dani? And are you calling each plot a time series?

The number of lat and long coordinates refers to how many coordinates there are per plot/study - e.g., it could be a study with fixed plots but they only gave the coordinates for the center point of the study and not each individual plot or something like that.

It would be good to have a histogram of how study area varies and see the distribution as the decision for a rarefaction is not based on below or above 96km2 (that is just a number that people chose in the original BioTIME rarefaction). For example, if you have 10 studies with area of 10km2, 80 with 25km2, etc. that is still not even. In the context of your specific question, studies with larger areas might be exposed to more roads and be more accessible purely because they cover larger areas. So the idea of the rarefaction is to standardise that. But you can also have study area as a variable in your models to try and partially account for the potential confounding effect of study area.

Sure, I can meet towards the end of the week. If there is a lab meeting on Friday, how about we meet after that?

**Comment by DaniGargya** [comment]
Hey @gndaskalova @IslaMS 

I am referring to terrestrial studies only. Time-series are the plots.

Here is a histogram of how study area varies:
![area_hist_base](https://user-images.githubusercontent.com/32903053/76414098-9389aa00-638e-11ea-914b-13b1e4e1596d.png)

I have also logged the area as the it was very right-skewed.

![hist_log_area](https://user-images.githubusercontent.com/32903053/76414108-97b5c780-638e-11ea-9bd7-90288bcb4088.png)

I guess the study area is very uneven according to these histograms?

Friday after the lab meeting sounds good to me!

**Comment by DaniGargya** [comment]
Hey @gndaskalova !
are you free sometime on monday? I still have some pressing questions about the data and the plot/ time-series level which are confusing my further analysis. 
Have a good sunday,
Dani

**Comment by gndaskalova** [comment]
Hi @DaniGargya Sorry I wasn't around on Skype after lab meeting on Friday! Sure, how about 4pm on Monday on skype?

**Comment by DaniGargya** [comment]
Tomorrow at 4pm sounds great. Talk to you then!

**Comment by DaniGargya** [comment]
Hey @gndaskalova 
I am still trying to figure out the code for calculating jaccard dissimilarity. Although I managed to do it for 1 plot, I am struggling to scale it up. This is the for loop I came up with but it is always giving me an error message for the spread() function. Do you have any tip of what other approach I could try and whether I set up the function in a wrong way?

```
# create different dataframes (with summed abundances per plot, year and species)
bio_t_list <- split(bio_turnover, bio_turnover$STUDY_ID_PLOT)

# create empty list
jaccard_list <- list()

# for loop
for (i in 1:length(bio_t_list)) {
  matrix <- tidyr::spread(bio_t_list[[i]]$GENUS_SPECIES, bio_t_list[[i]]$Abundance, fill = 0)
  matrix_s <- select(matrix, - STUDY_ID_PLOT, -YEAR)
  jaccard <- vegdist(matrix_s, method = "jaccard")
  dat <- data.frame(STUDY_ID_PLOT, jaccard)
  jaccard_list[[i]] <- dat
}
```

Also I realized that I might have filtered too much before doing the CENT_LAT = Latitude test.. It seems like out of 5788 plots, only 2193 have unique lat/long data. However, a lot of the plots are under 1km². Only 614 plots are above 1km² coming from 3 studies. Their areas are 2, 30 and 64 km². 

- for the studies < 1km² can I use the CENT_LAT/LONG data, assuming that all the plots were within the 1km² of the CENT_LAT/LONG given? That would also mean they would all have the same accessibility score.

- do I need to exclude the studies with area > 1km² which only have 1 CENT_LAT/LONG value and then do the sensitivity analysis with them later?

Have a lovely day,
Dani

**Comment by gndaskalova** [comment]
Hey @DaniGargya 

What is the error you get regarding `spread()`?

**Comment by DaniGargya** [comment]
Error in UseMethod("spread_") : 
  no applicable method for 'spread_' applied to an object of class "factor"

**Comment by DaniGargya** [comment]
but it does not have to do with the class itself, as i have tried to change it

**Comment by DaniGargya** [comment]
Hey @gndaskalova ,

I am unfortunately still stuck with the jaccard calculation. I have tried to use pipes instead and I don't get the spread error message anymore. I have also tried to use the betapart package (as well as vegan) from the s change workshop. BUT somehow it calculates the dissimilarity index between all available plots (eg if I filter for 2 plots only to start with, I get 6 different numbers as I have 2 different years for each plot). 

Here is the code (or it is on the data_transformation script https://github.com/DaniGargya/dissertation/blob/master/scripts/data_transformations.R

````
bio_t_list <- split(bio_turnover, unique(bio_turnover$STUDY_ID_PLOT))

jaccard_list <- data.frame(STUDY_ID_PLOT = unique(bio_turnover$STUDY_ID_PLOT), jaccard = NA)

for (i in 1:length(bio_t_list)) {
  bio_t_list[[i]] <- bio_t_list[[i]] %>% 
    spread(GENUS_SPECIES, Abundance, fill = 0) %>% 
    dplyr::select(-STUDY_ID_PLOT, -YEAR) %>% 
    vegdist(method = "jaccard", binary = TRUE) -> jaccard
  
  jaccard_list[i, "jaccard"] <- jaccard
}
````

Is there any chance to catch up with you on skype tomorrow or on friday?

Thanks,
Dani

**Comment by IslaMS** [comment]
Hi Dani,

Is this part of the line a problem?  It looks like you are overwriting the data frame.

<img width="291" alt="image" src="https://user-images.githubusercontent.com/5587986/77569600-5959f580-6ec2-11ea-9fa3-e6bce52be628.png">

I also am not sure about the '-> jaccard part'. 

I haven't yet run the code though.  

Can you confirm for me that this does not work?  I am just writing things by memory.  You should check each line and make sure to implement things correctly.  

Use "pivot_wider" the recent replacement for spread.
https://tidyr.tidyverse.org/reference/spread.html

jaccard_df <- bio_turnover %>% 
pivot_wider(GENUS_SPECIES, Abundance) %>%
group_by(STUDY_ID_PLOT) %>%

something here to put things into a matrix format
perhaps using the matrify() function
https://www.rdocumentation.org/packages/labdsv/versions/1.8-0/topics/matrify

do(jaccard = vegdist(method = "jaccard", binary = TRUE, data = .))

Or you could implement the same thing using a loop.  Gergana may have a code chunk that does this already.

If that doesn't help, let me know and I will try running things on my end.

Isla

**Comment by gndaskalova** [comment]
Hi @DaniGargya 

Did Isla's suggestion help?

Regarding this:

"I have also tried to use the betapart package (as well as vegan) from the s change workshop. BUT somehow it calculates the dissimilarity index between all available plots (eg if I filter for 2 plots only to start with, I get 6 different numbers as I have 2 different years for each plot)."

But that's fine? Isn't this what you need? You then keep the second value for each plot (turnover in the final year relative to the first). The turnover in the first year should be zero (cause it's looking at the turnover in year 1 relative to year 1). Then if you get another set of values, that'd be the two plots relative to each other in year 1 and then in year 2, so that would be turnover among the plots (i.e., across space). Earlier on you had some thoughts about using spatial turnover too. But for now, I don't think it's "bad" if you get more turnover values, as you can filter for the ones you need.

Does that make sense?

I am free after lab meeting so we can talk further then.

Have a nice afternoon,
Gergana

**Comment by DaniGargya** [comment]
hey @gndaskalova  and @IslaMS ,

thanks for the help and the suggestions. I am still struggling to understand the different values I'm getting, whether they are the right ones (because right now the code is creating matrices across all sites and not for each one) and which of the outputs I'm supposed to use.

I will keep working on it tomorrow morning before the lab meeting and then I will also be able to narrow down my questions.

See you then,
Dani

**Comment by gndaskalova** [comment]
Hi @DaniGargya 

Sounds good. I think since you know how to do it for 1 plot, you can compare results - e.g., if you calculate turnover for 1 plot in year 2 relative to year 1, then for 2 plots in year 1, the two plots in year 2, plot 2 in year 2 relative to year 1. Then you can compare if those values are the same as what you get out of the loop.

If you are using betapart, also remember that it will give you three turnover values - total beta diversity change, turnover and nestedness. There are more details in the paper about the package. So if you are using betapart and get 6 values when doing it for 2 plots, that'd be the right number of values.

Till tomorrow,
Gergana

**Comment by DaniGargya** [comment]
Hey @IslaMS and @gndaskalova ,

I talked to Gergana on friday  about the calculation of jaccard which I am still stuck with. The problem was that Gergana couldn't run vegan on her computer so she couldn't have a look at the code herself. 

I have tried to rerun the code without the loop and I am actually getting the right numbers. Problem now is that they are one of many numbers in my output matrix. I have recognized the pattern with which I could extract them, but I could not yet think of a way to do that. The pattern is two down and then two to the right:

<img width="253" alt="screenshot_jtu" src="https://user-images.githubusercontent.com/32903053/77915071-c38de400-728e-11ea-9921-abf4eefdb763.png">

I have tried to google for a solution but I did not get very far yet. 

Do you have any experience with extracting a sequence like that? Or should I go back and try and figure out the loop (for that I'm also very stuck what else to try)?

Here is a cleaned up question script with all the important code:
https://github.com/DaniGargya/dissertation/blob/master/scripts/question_script_Dani_Mar20.R
(data is also in the repo)

Thanks,
Dani

**Comment by IslaMS** [comment]
Hi @DaniGargya,

I can help you out with this today.  I have the code running on my end.  Do you want to set up a Skype meeting so that we can go through things together?  I think that might be more productive than me working on things on my own.  If you want to subset values from a matrix like this that is pretty straight forward (see below), but I think we should be able to set up your code in a more straight forward way rather than do that - though I could of course be wrong!

To get the first element of a matrix do this:
jtu[1]

To get the 6th column of the 5th row do this:
jtu[6,5]

Isla

**Comment by DaniGargya** [comment]
Hi @IslaMS ,
skype meeting sounds great! When would you be free? Sometime in the afternoon?

Thanks,
Dani

**Comment by IslaMS** [comment]
Do you want to go for 1:30pm?  I'll go do my outdoor time now while it is still sunny!

**Comment by DaniGargya** [comment]
1.30 sounds good! Enjoy outdoors :)

**Comment by IslaMS** [comment]
In advance of our meeting, can you set up a pipe to get down to the level and exact dataframe for which you want to calculate the Jaccard index?  And can you indicate your planned workflow and what you want your final dataframe to look like as notes in the question script - or another script that we can work in.  Just so I can see where we are heading and where the problem points are.  I think doing things in pipe rather than a loop is going to be easiest for you, but we can convert back to a loop if that is the only way, but using that same workflow.

The sun is gone now that I am ready to go out, but I will go outside anyways!

See you soon.

**Comment by IslaMS** [comment]
Hey @DaniGargya, 

Just so you know, I don't think you are seeing my Skype messages?  I am standing by, but I also said I would chat with Shawn this afternoon.  So maybe I should go ahead and meet with him now?

**Comment by IslaMS** [comment]
Hi @DaniGargya,

I have had a go at your programming issues this morning.  I have not been able to get a pipe to work, because I can't figure out how to get pivot_wider to work at the plot level - I am sure there is a way, I just can't figure it out yet.  So I switched over to the loop approach and I have a functioning loop for you in the new script that I made in your scripts folder.  I also switched your beta diversity function, as I think the one you were using has more complex output - the full matrix instead of three numbers.  There seem to be many options in the betapart package though (https://cran.r-project.org/web/packages/betapart/betapart.pdf), so maybe chat with @gndaskalova about the best one to use?  Maybe we can run through things at some point today?  I have a meeting now, but am free later on.

Isla

**Comment by DaniGargya** [comment]
Hey @IslaMS ,
thanks for sharing the script with the working loop! I also didn't get any further with the pipe... 

Running through things together sounds good. I am quite flexible in terms of time. What do you think about 3pm?

**Comment by IslaMS** [comment]
Sounds good!  See you then.

**Comment by IslaMS** [comment]
Hey @DaniGargya,

Just to let you know that I added richness into the loop as it was an easy thing to do and might be useful for you!

Isla

**Comment by DaniGargya** [comment]
i've just pulled, thanks @IslaMS !!
